### PR TITLE
Removed email address

### PR DESCRIPTION
**Pull request by Natfan**
See https://twitter.com/ReadingUniHack/status/956989118151569408 for justification.

### CODE REVIEW

**Comment by andrejusk** [comment]
I'm sorry you feel this way.

**Comment by Natfan** [comment]
Why advertise an email address that you can't access?

**Comment by andrejusk** [comment]
Not exactly sure how listing forms of communication in the footer is advertising, but we do have access to them; just not enough resources to check them frequently.

**Comment by Natfan** [comment]
Ah, the way that the tweet was worded was that the emails were not accessible at all.

**Pull request closed without merging**
